# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05f1d1347b47e88b515bf25085b8bee8"
name = "cash"
handle = "cash-6"
application_url = "https://example.com/"
embedded = true

[build]
dev_store_url = "code-qa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_payment_customizations,write_payment_customizations"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
